version: "3"
services:
  xnat-web:
    image: 127.0.0.1:5000/dcm4chee-docker/xnat
    build:  
      context: ./xnat
      args:
        XNAT_VER: '1.7.6'
        XNAT_DATASOURCE_DRIVER: 'org.postgresql.Driver'
        XNAT_DATASOURCE_URL: 'jdbc:postgresql://xnat-db/xnat'
        XNAT_DATASOURCE_USERNAME: 'xnat'
        XNAT_DATASOURCE_PASSWORD: 'xnat'
        XNAT_HIBERNATE_DIALECT: 'org.hibernate.dialect.PostgreSQL9Dialect'
        TOMCAT_XNAT_FOLDER: ROOT
        XNAT_ROOT: /data/xnat
        XNAT_HOME: /data/xnat/home
    ports:
      - "8081:8080"
      - "8000:8000"
      - "22:22"
    volumes:
      - /opt/xnat/plugins:/data/xnat/home/plugins
      - /opt/xnat-data/home/logs:/data/xnat/home/logs
      - /opt/xnat-data/archive:/data/xnat/archive
      - /opt/xnat-data/build:/data/xnat/build
      - /opt/run/docker.sock:/var/run/docker.sock
    depends_on:
      - xnat-db
    environment:
      - CATALINA_OPTS=-Xms128m -Xmx2048m -Dxnat.home=/data/xnat/home -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000
      - XNAT_HOME=/data/xnat/home
    deploy:
      placement:
        constraints: [node.hostname == node4]

  xnat-db:
    image: 127.0.0.1:5000/dcm4chee-docker/postgres
    build: ./postgres
    ports:
      - "5433:5433"
    environment:
        POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - /opt/postgres-data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints: [node.hostname == node4]

  xnat-nginx:
    image: 127.0.0.1:5000/dcm4chee-docker/nginx
    build: ./nginx
    ports:
      - "80:80"
    links:
      - xnat-web
    deploy:
      placement:
        constraints: [node.hostname == node4]
  ldap:
    image: dcm4che/slapd-dcm4chee:2.4.48-22.1
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "389:389"
    env_file: docker-compose.env
    volumes:
      - /opt/dcm4chee-arc/ldap:/var/lib/openldap/openldap-data
      - /opt/dcm4chee-arc/slapd.d:/etc/openldap/slapd.d
    deploy:
      placement:
        constraints: [node.hostname == node1]
  db:
    image: dcm4che/postgres-dcm4chee:12.2-22
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "5432:5432"
    env_file: docker-compose.env
    volumes:
      - /opt/dcm4chee-arc/db:/var/lib/postgresql/data
    deploy:
      placement:
        constraints: [node.hostname == node2]
  arc:
    image: dcm4che/dcm4chee-arc-psql:5.22.1
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "9993:9993"
      - "11112:11112"
      - "2762:2762"
      - "2575:2575"
      - "12575:12575"
    env_file: docker-compose.env
    environment:
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432
    depends_on:
      - ldap
      - db
    volumes:
      - /opt/dcm4chee-arc/wildfly:/opt/wildfly/standalone
      - /opt/dcm4chee-arc/storage:/storage
    deploy:
      placement:
        constraints: [node.hostname == node3]
